config/routes.rb
News::Application.routes.draw do
  get "sessions/create"

  get "sessions/destroy"

  get "session/create"

  get "session/destroy"

  resources :cats
  match '/images/new/(:id)' => 'images#new', :as => 'image_new'
  resources :images

  resources :entries do
    resources :images
  end
  resources :sessions

  root :to => 'entries#index'

  match '/login', :controller => 'sessions', :action => 'new'
  match '/logout', :controller => 'sessions', :action => 'destroy'
  match '/news', :controller => 'entries', :action => 'index'
  match '/news/:id/:name', :controller => 'entries', :action => 'index'

  match '/update_main', :controller => 'entries', :action => 'update_main'

  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :cat
	validates_presence_of :title, :description
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_filter :authorize, :except => [:show, :index]
  # GET /entries
  # GET /entries.json
  def index
    if params[:id]
      @entries = Entry.where(:cat_id => params[:id])
    else
      @entries = Entry.all
    end
    
      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

def news
    if params[:id]
      @entries = Entry.where(:cat_id => params[:id])
    else
      @entries = Entry.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end


  def update_main
    @entry = Entry.find(params[:entrie_id])
    
    @entry.mainimg = params[:setmain]
    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "show" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new
    @cats = Cat.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper

	def bringimages(entrie)
		@images = Image.where(:entrie_id => entrie)
	end

end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="field">

    <%= f.label "category" %><br />
    <%= collection_select(:entry, :cat_id, Cat.all, :id, :name)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<% if admin? %>
<p class="adminoption"><%= link_to 'New Entry', new_entry_path %></p>
<% end %>

<% if @entries.empty? %>
<p>Sorry =( <br /> no news in this category </p>
<% end %>

<% @entries.each do |entry| %>
<article>
<h2><%= link_to entry.title,entry %></h2>
<p class="category">Category: 
	<a href="/news/<%= entry.cat_id %>/<%= nombrecat(entry.cat_id)%>">
	<%= nombrecat(entry.cat_id)%></a>
</p>

<p>
<% if entry.mainimg != nil%>
<% bringmainimg(entry.id) %>
<a rel="facebox" href="/images/800-<%= @image_file %>"><img src="/images/tn-s-c-150-<%= @image_file %>" title=" @image_title"  width="100" style="float:left;margin:8px 8px 0 0; display:inline;"/></a>
<% end %>
<%= entry.description %>
</p>


<% if admin? %>
<div class="adminoption">
<%= link_to 'Add + images', image_new_path(entry.id) %>
<%= link_to 'Edit new', edit_entry_path(entry) %><%= link_to 'Destroy new', entry, confirm: 'Are you sure?', method: :delete %>
</div>
<% end %>
<hr>
</article> 
<% end %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>




<h1><%= @entry.title %></h1>

<p class="category">
Category: 
<a href="/news/<%= @entry.cat_id %>/<%= nombrecat(@entry.cat_id)%>"><%= nombrecat(@entry.cat_id)%></a>
</p>

<p><%= @entry.description %></p>

<% @images = bringimages(@entry.id)%>


<% if admin? %>
<%= form_tag( { :action => 'update_main' } ) %>
<% @images.each do |img| %>
<div class="imglist" style="border:1px solid #e2e2e2; float:left;">
<img src="/images/tn-s-c-150-<%= img.filename %>" title="<%= img.title %>"  width="80"/>
<% if admin? %>
<p class="adminoption"><%= link_to 'Delete', img, confirm: 'Are you sure?', method: :delete %></p>
<p class="adminoption">Set main: <br/><%= radio_button_tag 'setmain', img.id, true	%></p>
<% end %>
</div>
<% end %>
<%= hidden_field_tag 'entrie_id', @entry.id %>

<%= button_tag "Set main image" %>
<% else %>
<% @images.each do |img| %>
<div class="imglist" style="float:left;">
<a rel="facebox" href="/images/800-<%= img.filename %>">
<img src="/images/tn-s-g-150-<%= img.filename %>" title="<%= img.title %>"  width="80"/>
</a>
</div>
<% end %>

<% end %>
<% if admin? %>
<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>
<% end %>