config/routes.rb
News::Application.routes.draw do
  get "sessions/create"

  get "sessions/destroy"

  get "session/create"

  get "session/destroy"

  resources :cats
  match '/images/new/(:id)' => 'images#new', :as => 'image_new'
  resources :images

  resources :entries do
    resources :images
  end
  resources :sessions

  root :to => 'entries#index'

  match '/login', :controller => 'sessions', :action => 'new'
  match '/logout', :controller => 'sessions', :action => 'destroy'
  match '/news', :controller => 'entries', :action => 'index'
  match '/news/:id/:name', :controller => 'entries', :action => 'index'

  match '/update_main', :controller => 'entries', :action => 'update_main'

  

end

app/models/cat.rb
class Cat < ActiveRecord::Base
	has_many :entries
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cats }
    end
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
    @cat = Cat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cat }
    end
  end

  # GET /cats/new
  # GET /cats/new.json
  def new
    @cat = Cat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cat }
    end
  end

  # GET /cats/1/edit
  def edit
    @cat = Cat.find(params[:id])
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(params[:cat])

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render json: @cat, status: :created, location: @cat }
      else
        format.html { render action: "new" }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cats/1
  # PUT /cats/1.json
  def update
    @cat = Cat.find(params[:id])

    respond_to do |format|
      if @cat.update_attributes(params[:cat])
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to cats_url }
      format.json { head :ok }
    end
  end
end

app/helpers/cats_helper.rb
module CatsHelper

	def nombrecat(idcat)
		cat = Cat.find(idcat)
		category_name = cat.name
		return category_name
	end


end

app/views/cats/_categories.html.erb
<% @categories = Cat.all %>
<li><a href="/news/">All</a></li>
<% @categories.each do |cat| %>
	<li><a href="/news/<%= cat.id %>/<%= cat.name %>"><%= cat.name %></a></li>
<% end %>

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<h1>Listing cats</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cats.each do |cat| %>
  <tr>
    <td><%= cat.name %></td>
    <td><%= link_to 'Show', cat %></td>
    <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
    <td><%= link_to 'Destroy', cat, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cat.name %>
</p>


<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>