config/routes.rb
News::Application.routes.draw do
  get "sessions/create"

  get "sessions/destroy"

  get "session/create"

  get "session/destroy"

  resources :cats
  match '/images/new/(:id)' => 'images#new', :as => 'image_new'
  resources :images

  resources :entries do
    resources :images
  end
  resources :sessions

  root :to => 'entries#index'

  match '/login', :controller => 'sessions', :action => 'new'
  match '/logout', :controller => 'sessions', :action => 'destroy'
  match '/news', :controller => 'entries', :action => 'index'
  match '/news/:id/:name', :controller => 'entries', :action => 'index'

  match '/update_main', :controller => 'entries', :action => 'update_main'

  

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :entry
	validates_presence_of :title, :filename
	validates_presence_of :entrie_id
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    if (params[:image][:filename])
    #function in manage_images.rb
    process_image(tmp = params[:image][:filename].tempfile)
    end
    identrie = params[:image][:entrie_id]
    respond_to do |format|
      if @image.save
        format.html { redirect_to entries_path, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
     
        format.html { redirect_to image_new_path(identrie),  notice: ':('  }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    #si viene imagen en los parametros la subo
    if (params[:image][:filename])
    #traigo el nombre de la iamgen anterior al cambio
    imageold = @image.filename
    process_image(tmp = params[:image][:filename].tempfile)

    #remuevo la anterior
    remove_image_file(imageold)
    end

    #si viene titulo nuevo lo actualizo
    if(params[:image][:title])
    @image.title = params[:image][:title]
    end


    respond_to do |format|
      if @image.save #update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    
    imagen = @image.filename
    
    #function in manage_images.rb
    remove_image_file(imagen)

    @image.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end

########### IMAGES FUNCTIONS ###########

############ BASIC PROCESS OF IMAGE ############
###### check if is valid image extencion #######
###### upload temporal file to server    #######
###### create thumbnails from original image ###

def process_image(tmp)
  random  = 2 + rand(10**24-10)+10
  path ="public/images/"
  file = File.join(path, random.to_s + "-" + params[:image][:filename].original_filename)

  #check extencion
    ext = File.extname(file)
    if ext.upcase == ".JPG"
      extfinal = ".jpg"
      imagevalid = true
    elsif ext.upcase == ".JPEG"
      extfinal = ".jpg"
      imagevalid = true
    elsif ext.upcase == ".GIF"
      extfinal = ".gif"
      imagevalid = true
    elsif ext.upcase == ".PNG"
      extfinal = ".png"
      imagevalid = true
    end 
    
  if imagevalid == true 

  #Subo la imagen original recibida
  FileUtils.cp tmp.path, file

  archivo_final = uploadoriginal(file,path)

  #utilizo su nombre
  filenamethumb = random.to_s + "-" + params[:image][:filename].original_filename
  #width desired / ancho deseado
  w = 150
  #function call / llamada a la funcion
  hubermann_thumbnail(path, filenamethumb,w,square=true, bw=true, q=99)
  hubermann_thumbnail(path, filenamethumb,w,square=true, bw=false, q=99)


  FileUtils.rm file


  @image.filename = archivo_final
  #end unless valid image
  else
  @image.filename = nil

  end
end  

###### UPLOAD BIGGER IMAGE (800px) ######
def uploadoriginal(file,path)
  ext = File.extname(file)
    if ext.upcase == ".JPG"
      extfinal = ".jpg"
    elsif ext.upcase == ".JPEG"
      extfinal = ".jpg"
    elsif ext.upcase == ".GIF"
      extfinal = ".gif"
    elsif ext.upcase == ".PNG"
      extfinal = ".png"
    end 


    #nombre original de la imagen
    filename_orig = File.basename(file, '.*')

    #remove white space in image name
    filename_orig = filename_orig.gsub(" ","-")

    width = 800

    image = Magick::Image.read(file).first

    widthimage = image.columns
    heightimage = image.rows
    height = (width * heightimage) / widthimage
    thumbnail = image.thumbnail(width, height)


    finalname = path + "800-" + filename_orig + extfinal
    q=99
    thumbnail.write(finalname){ self.quality = q }
    return filename_orig + extfinal
    
end

###### HUBERMANN THUMBNAILS ######
def hubermann_thumbnail(path,filename, w, square, bw,q)
  width = w

  image = Magick::Image.read(path+"/"+filename).first

  ext = File.extname(filename)
  if ext.upcase == ".JPG"
    extfinal = ".jpg"
  elsif ext.upcase == ".JPEG"
    extfinal = ".jpg"
  elsif ext.upcase == ".GIF"
    extfinal = ".gif"
  elsif ext.upcase == ".PNG"
    extfinal = ".png"
  end 

  #nombre original de la imagen
  filename_orig = File.basename(filename, '.*')

  #remove white space in image name
  filename_orig = filename_orig.gsub(" ","-")


  unless square 
    #proportional
    widthimage = image.columns
    heightimage = image.rows
    height = (width * heightimage) / widthimage
    thumbnail = image.thumbnail(width, height)
    finalname = path +  "/tn-p-" 
  else
    #square
    thumbnail = image.resize_to_fill(width, width)
    finalname = path +  "/tn-s-"
  end
  #grayscale 
  if bw == true
    thumbnail = thumbnail.quantize(256, Magick::GRAYColorspace)
    finalname = finalname + "g-"
  else
    finalname = finalname + "c-"
  end
  finalname = finalname + w.to_s + "-" + filename_orig + extfinal

  thumbnail.write(finalname){ self.quality = q }

end
###### REMOVE IMAGE ######
def remove_image_file(imagefile)
if File.exists?('public/images/800-' + imagefile)
    path = 'public/images/'
    File.delete('public/images/800-' + imagefile)
    File.delete('public/images/tn-s-c-150-' + imagefile)
    File.delete('public/images/tn-s-g-150-' + imagefile) 
    end
end

########### END IMAGES FUNCTIONS ###########


end

app/helpers/images_helper.rb
module ImagesHelper

	def bringmainimg(identry)
		entry = Entry.find(identry)

		image = Image.find(entry.mainimg)

		@image_file =  image.filename 
		@image_title = image.title 
	end

end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :filename %><br />
    <%= f.file_field :filename , :accept => 'image/png,image/gif,image/jpeg' %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
   
    <%= f.hidden_field :entrie_id, :value => params[:id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Filename</th>
    <th>Entrie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.title %></td>
    <td><%= image.filename %></td>
    <td><%= image.entrie_id %></td>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @image.title %>
</p>

<p>
  <b>Filename:</b>
  <%= @image.filename %>
</p>

<p>
  <b>Entrie:</b>
  <%= @image.entrie_id %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>